name: space_scutum_test_task
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^9.1.0  
  # Value equality
  equatable: ^2.0.7
  # Declarative routing
  go_router: ^14.8.1
  # Local Database
  hive_flutter: ^1.1.0
  # Service locator for dependency injection
  get_it: ^8.0.3
  # Path provider
  path_provider: ^2.1.5
  # JSON serialization
  json_annotation: ^4.8.1
  # HTTP client for API requests
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^5.0.0
  # Code generation tool
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
