name: space_scutum_test_task
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0  
  go_router: ^14.8.1
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
